# Generated by Django 3.0.6 on 2020-08-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Film name')),
                ('producer', models.CharField(max_length=100, verbose_name='Produser')),
                ('ceated_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('warning_age', models.IntegerField(default=0, verbose_name='Warning age')),
                ('description', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(blank=True, upload_to='media', verbose_name='Image')),
                ('view', models.IntegerField(default=0, verbose_name='Views')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_author', models.CharField(max_length=100, verbose_name='Review author')),
                ('review_text', models.TextField(verbose_name='Text')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Film')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Genre'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_author', models.CharField(max_length=100, verbose_name='Answer author')),
                ('answer_text', models.TextField(verbose_name='Text')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Actor name')),
                ('another_he_films', models.TextField(verbose_name='Actor another films')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.Film')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
    ]
