# Generated by Django 3.0.6 on 2020-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, height_field=600, upload_to='media', verbose_name='Image', width_field=500),
        ),
    ]
