# Generated by Django 3.0.6 on 2020-08-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20200810_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Image'),
        ),
    ]
