# Generated by Django 3.0.6 on 2020-08-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20200810_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='media', verbose_name='Image')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.Film')),
            ],
        ),
    ]
