# Generated by Django 3.0.6 on 2020-08-18 11:33

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_filmshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmshots',
            options={'verbose_name': 'Filmshot', 'verbose_name_plural': 'Filmshots'},
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
