# Generated by Django 3.0.6 on 2020-08-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20200818_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='another_he_films',
            new_name='another_films',
        ),
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.TextField(null=True, verbose_name='Actor description'),
        ),
        migrations.AddField(
            model_name='actor',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Image'),
        ),
    ]
