# Generated by Django 3.0.6 on 2020-08-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_userphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphoto',
            options={'verbose_name': 'UserPhoto', 'verbose_name_plural': 'UserPhotos'},
        ),
        migrations.CreateModel(
            name='LikedFilmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='film.Film')),
            ],
        ),
    ]
