# Generated by Django 3.0.6 on 2020-08-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0009_auto_20200829_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedfilms',
            options={'verbose_name': 'Likedfilm', 'verbose_name_plural': 'Likedfilms'},
        ),
        migrations.RemoveField(
            model_name='likedfilms',
            name='film',
        ),
        migrations.AddField(
            model_name='likedfilms',
            name='films',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.Film'),
        ),
        migrations.AddField(
            model_name='likedfilms',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
