# Generated by Django 3.0.6 on 2020-08-31 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0011_auto_20200829_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreatedFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.Film')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
