# Generated by Django 3.0.6 on 2020-09-03 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0012_usercreatedfilms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercreatedfilms',
            options={'verbose_name': 'Usercreatedfilm', 'verbose_name_plural': 'Usercreatedfilms'},
        ),
        migrations.CreateModel(
            name='UserDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
