# Generated by Django 3.0.6 on 2020-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_auto_20200903_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdescription',
            options={'verbose_name': 'Userdescription', 'verbose_name_plural': 'Userdescriptions'},
        ),
    ]
